let num;    
num = 123;    
alert(num); 
let d = 4 / 2;
alert(d);
let a = 10;
let b = 3;
alert(a ** b); 
let str1 = 'abc';
let str2 = 'def';
alert(str1 + ' ' + str2);
alert('abcde'.length);
alert(-1 / 0);
let num1 = 123;
let num2 = 456;
console.log(num1, num2);
const pi = 3.14;
let num0 = parseInt('12px');
let str = String(123);
let num9 = 12345;
let str0 = String(num9); 
alert(str0.length);
alert(true + 1);     
alert(true + true);
let str3 = 'abcde';
alert(str3[0]); 
alert(str3[1]); 
alert(str3[2]); 